### ISSUE TITLE
Could not pass event InventoryClickEvent to BlobLib v1.698.30

### ISSUE THREAD

**Issue by servicomcr** [anjoismysign/BlobLib#2]
Could not pass event InventoryClickEvent to BlobLib v1.698.30
java.lang.NullPointerException: buttonRangeKey is not an InventoryButton
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.entities.inventory.VariableSelector.loadCustomPage(VariableSelector.java:185) ~[BlobLib-1.698.30.jar:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.entities.BlobEditor.manage(BlobEditor.java:423) ~[BlobLib-1.698.30.jar:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.api.BlobLibInventoryAPI.customEditor(BlobLibInventoryAPI.java:648) ~[BlobLib-1.698.30.jar:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.api.BlobLibInventoryAPI.customEditor(BlobLibInventoryAPI.java:566) ~[BlobLib-1.698.30.jar:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.api.BlobLibInventoryAPI.customEditor(BlobLibInventoryAPI.java:539) ~[BlobLib-1.698.30.jar:?]
        at BlobStones-1.0.16.jar/us.mytheria.blobstones.engine.ProtectionStonesEngine.openManageMembers(ProtectionStonesEngine.java:322) ~[BlobStones-1.0.16.jar:?]
        at BlobStones-1.0.16.jar/us.mytheria.blobstones.engine.ProtectionStonesEngine.lambda$registerManageProtection$1(ProtectionStonesEngine.java:69) ~[BlobStones-1.0.16.jar:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.entities.inventory.InventoryDataRegistry.processSingleClickEvent(InventoryDataRegistry.java:131) ~[BlobLib-1.698.30.jar:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.managers.InventoryTrackerManager.lambda$onClick$0(InventoryTrackerManager.java:125) ~[BlobLib-1.698.30.jar:?]
        at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1016) ~[?:?]
        at BlobLib-1.698.30.jar/us.mytheria.bloblib.managers.InventoryTrackerManager.onClick(InventoryTrackerManager.java:119) ~[BlobLib-1.698.30.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3204) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by anjoismysign** [comment]
Send full log.

The issue is only possible if you deleted a section inside a BlobInventory, being specific a BlobInventory used as a VariableSelector

**Comment by anjoismysign** [comment]
It seems it is inside a BlobInventory that gets opened whenever interacting with the open members UI in BlobStones

**Comment by anjoismysign** [comment]
![image](https://github.com/user-attachments/assets/5d4cfbc8-1745-4cd1-817d-28fc162e1cab)

The issue is inside ManageMembers.yml
It seems you deleted the "Members" InventoryButton (inside the Buttons section)

**Comment by anjoismysign** [comment]
It would be helpful if you could zip your BlobStones plugin directory and send it to me, since BlobStones has embedded localization (there are multiple ManageMembers files, one for each unique locale/language)

**Comment by servicomcr** [comment]
This happened after the update. that came out one of these days. I think that on Sunday, it was the update of the library, in fact I haven't touched anything about the plugin, I only installed it to test it

https://we.tl/t-PBO7y8ZFwx
